---
# tasks file for haproxy

- name: Install haproxy
  yum:
    name: haproxy
    state: latest
# - name: setup haproxy for kubernetes in /etc/haproxy/haproxy.cfg
#   template:
#     src: haproxy.cfg.j2
#     dest: /etc/haproxy/haproxy.cfg
#     owner: root
#     group: root
#     mode: "0644"
