---
# tasks file for haproxy

- name: Ensure the latest version of haproxy is installed
  become: true
  yum:
    name: haproxy
    state: latest

- name: Ensure required packages for ansible seboolean module are installed
  become: true
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - libselinux-python
      - libsemanage-python

- name: Ensure seboolean haproxy_connect_any is on
  become: true
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  notify:
    - Restart haproxy

- name: Ensure IP forwarding is on
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  notify:
    - Restart haproxy

- name: Ensure IP nonlocal binding is on
  become: true
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  notify:
    - Restart haproxy

- name: Ensure haproxy is configured in /etc/haproxy/haproxy.cfg
  become: true
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart haproxy

- name: Ensure haproxy is running
  become: true
  systemd:
    name: haproxy
    state: started
    enabled: yes
