---

- name: Install Docker for Kubernetes
  hosts: kubernetes
  vars:
    docker_version: 19.03.4
    containerd_version: 1.2.10
  tasks:          
  - name: Install required packages for Docker
    become: true
    yum:
      name:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
  - name: Add Docker repository
    become: true
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg
      state: present
  - name: Install Docker CE
    become: true
    yum:
      name:
      - containerd.io-{{ containerd_version }}
      - docker-ce-{{ docker_version }}
      - docker-ce-cli-{{ docker_version }}
  - name: Create Docker configuration directory /etc/docker
    become: true
    file:
      path: /etc/docker
      state: directory
      mode: '0755'
  - name: Create Docker configuration file at /etc/docker/daemon.json
    become: true
    copy:
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2",
          "storage-opts": [
            "overlay2.override_kernel_check=true"
          ]
        }
      dest: /etc/docker/daemon.json
  - name: Create directory /etc/systemd/system/docker.service.d
    become: true
    file:
      path: /etc/docker
      state: directory
      mode: '0755'
  - name: Restart & Enable Docker with a daemon-reload to pick up config changes
    become: true
    systemd:
      enabled: yes
      state: restarted
      daemon_reload: yes
      name: docker
