---
# Temp placeholder - will move to roles later
- name: Disable SELinux (not friendly with kubernetes)
  hosts: kubernetes
  tasks:
    - selinux:
      state: disabled

- name: install docker cluster-wide as the container runtime
  hosts: master_nodes, worker_nodes
  become: true
  roles:
    - docker

- name: bootstrap haproxy nodes
  hosts: haproxy_nodes
  become: true
  roles:
    - haproxy
    - keepalived
# - name: Display all variables/facts known for a host
#   debug:
#     var: hostvars
#     # verbosity: 4
