---
- name: Randomly generate a password for keepalived
  hosts: localhost
  tasks:
    - name: Randomly generate a password for keepalived
      set_fact:
        randomly_generated_keepalived_vrrp_auth_pass: "{{ (ansible_fqdn | password_hash('sha512') | password_hash('sha256'))[-9:-1] }}"

- name: Bootstrap load balancers with high availability
  hosts: haproxy_nodes
  roles:
    - role: firewalld_k8s
      vars:
        interfaces_connected_to_public:
          - eth0
        interfaces_connected_to_kubernetes:
          - eth1
        kubernetes_sources:
          - 10.0.0.10
          - 10.0.0.100
          - 10.0.0.101
          - 10.0.0.101
          - 10.0.0.102
          - 10.0.0.201
          - 10.0.0.201
          - 10.0.0.202
        ports_open_to_kubernetes:
          - 22/tcp # ssh
          - 6443/tcp # kube-apiserver
        ports_open_to_public:
          - 22/tcp # bastion
          - 80/tcp # http
          - 443/tcp # https

    - role: haproxy
      vars:
        load_balancers:
          - name: kube_apiserver
            listener_port: 6443
            target_port: 6443
            target_group: "master_nodes"
          - name: ingress_controller_http
            listener_port: 80
            target_port: 30080
            target_group: "worker_nodes"
          - name: ingress_controller_https
            listener_port: 443
            target_port: 30443
            target_group: "worker_nodes"

    - role: keepalived
      vars:
        inventory_hostname_short_active_server: haproxy-0
        inventory_hostname_short_standby_server: haproxy-1
        keepalived_vrrp_auth_pass: "{{ hostvars.localhost.randomly_generated_keepalived_vrrp_auth_pass }}"
        virtual_ip_address: 10.0.0.10
        process_to_monitor: haproxy
        vrrp_network_interface_active_server: eth1
        vrrp_network_interface_standby_server: eth1

    - role: docker # TEMP TESTING
# #
#
#
#
#
# - name: install docker as the container runtime
#   hosts: haproxy-0 # master_nodes, worker_nodes
#   become: true
#   roles:
#     - docker
#     -

# tasks:
#   - debug:
#       msg: "{{ (ansible_fqdn | password_hash('sha512') | password_hash('sha256'))[-9:-1] }}"
