---
# defaults file for firewalld_k8s

default_zone: public

public_interfaces: []
public_ports: []
public_sources: []
public_rich_rules: []

internal_interfaces: []
internal_ports: []
internal_sources: []
internal_rich_rules: []
