---
# defaults file for haproxy

# TCP Layer 4 Load Balancers

load_balancers:
  - name: kube_apiserver
    listener_port: 6443
    target_port: 6443
    target_group: "master_nodes"

  - name: ingress_controller_http
    listener_port: 80
    target_port: 30080
    target_group: "worker_nodes"

  - name: ingress_controller_https
    listener_port: 443
    target_port: 30443
    target_group: "worker_nodes"
