---
# tasks file for centos7_k8s

- name: Ensure the br_netfilter kernel module is loaded
  modprobe:
    name: br_netfilter
    state: present
    params: "numdummies=2"

- name: Ensure iptables can see bridged traffic for container traffic and kube-proxy
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Ensure SELinux is in permissive mode, logging actions that would be blocked
  selinux:
    policy: targeted
    state: permissive

- name: Disable swap since kubernetes and containerized workloads do not work well with it
  command: swapoff -a

- name: Ensure swap is disabled permanently in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
