---
# tasks file for docker

- name: install required packages for docker-ce
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: add docker-ce-stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: install docker-ce 19.3.8 for kubernetes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - containerd.io-1.2.13
      - docker-ce-19.03.8
      - docker-ce-cli-19.03.8

- name: create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: setup docker daemon for kubernetes in /etc/docker/daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart docker

- name: make sure docker is running
  service:
    name: docker
    state: started
