---
# tasks file for docker

- name: install required packages for docker-ce
  become: true
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: add docker-ce-stable repo
  become: true
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: install containerd.io-{{ containerd_io_yum_package_version }}
  become: true
  yum:
    name: containerd.io-{{ containerd_io_yum_package_version }}
    state: latest

- name: install docker-ce-{{ docker_ce_yum_package_version }} and install docker-ce-cli-{{ docker_ce_yum_package_version }}
  become: true
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce-{{ docker_ce_yum_package_version }}
      - docker-ce-cli-{{ docker_ce_yum_package_version }}

- name: create /etc/docker directory
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: setup docker daemon for kubernetes in /etc/docker/daemon.json
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart docker

- name: make sure docker is running
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
