---
# tasks file for docker_k8s

- name: Ensure required packages for docker-ce are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Ensure docker-ce-stable repo is available to yum
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Ensure containerd.io-{{ containerd_io_yum_package_version }} is installed
  yum:
    name: containerd.io-{{ containerd_io_yum_package_version }}
    state: latest

- name: Ensure docker-ce-{{ docker_ce_yum_package_version }} and docker-ce-cli-{{ docker_ce_yum_package_version }} are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce-{{ docker_ce_yum_package_version }}
      - docker-ce-cli-{{ docker_ce_yum_package_version }}
  notify:
    - Restart docker

- name: Ensure /etc/docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: "0755"
  notify:
    - Restart docker

- name: Ensure docker daemon is configured for kubernetes at /etc/docker/daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart docker

- name: Ensure docker is running
  systemd:
    name: docker
    state: started
    enabled: yes
